FILE = SDL_10.cpp

# CC especifica o compilador usado
CC = g++

# COMPILER_FLAGS especifica as opcoes de compilacao adicionais sendo usadas
COMPILER_FLAGS = 

# LINKER_FLAGS especifica as bibliotecas que estamos vinculando
LINKER_FLAGS = -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf

# EXE especifica o nome do nosso executavel
EXE = prog

# Compilando o executavel...
all : $(FILE)
	$(CC) $(FILE) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(EXE)